# Generated by Django 5.0.7 on 2024-08-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='imagepath',
            field=models.CharField(default='path', max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='venu', max_length=50),
            preserve_default=False,
        ),
    ]
