# Generated by Django 5.0.7 on 2024-08-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_imagepath_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='shortdescription',
            field=models.TextField(null=True),
        ),
    ]
