# Generated by Django 5.0.7 on 2024-08-07 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_shortdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=100)),
                ('mail1', models.EmailField(max_length=254)),
                ('mail2', models.EmailField(max_length=254)),
                ('participant1', models.CharField(max_length=75)),
                ('mail3', models.EmailField(max_length=254)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.event')),
            ],
        ),
    ]
