# Generated by Django 5.0.7 on 2024-08-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='participant2',
            field=models.CharField(default='test', max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='participant3',
            field=models.CharField(default='test', max_length=75),
            preserve_default=False,
        ),
    ]
