# Generated by Django 5.0.7 on 2024-08-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_submission_contact_alter_submission_mail2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='limit',
            field=models.PositiveIntegerField(default=60),
            preserve_default=False,
        ),
    ]
