# Generated by Django 5.0.7 on 2024-08-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_submission_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='limit',
        ),
        migrations.AddField(
            model_name='event',
            name='limit',
            field=models.PositiveIntegerField(default=60),
            preserve_default=False,
        ),
    ]
